### Obtener todos los usuarios
GET http://localhost:3000/api/v1/usuarios
Content-Type: application/json
#x_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiJkZjgzNWI3ZS03M2Q1LTRkNWYtOWVkZS1lYjQzZDg3N2EzMWIiLCJlbWFpbCI6Impvc2VsYWx1ekB1c2VyLmNvbSIsInVzZXJuYW1lIjoiam9zZSBsYSBsdXoiLCJpYXQiOjE3NDI0ODQ0ODgsImV4cCI6MTc0MjQ4ODA4OH0.jWCKBPB8HX9WYk6PShq8MQYeiaHKi0AnBu9i29HCROI

### Obtener usuario por id
GET http://localhost:3000/api/v1/usuarios/382f6cae-83c6-43e6-b3cf-e764eb15afe7

### Crear un usuario
POST http://localhost:4000/api/v1/usuarios
Content-Type: application/json

{
  "username": "joedoe",
  "email": "joedoe@user.com",
  "password": "123456"
}
