### Obtener todos los usuarios
GET http://localhost:3000/api/v1/usuarios

### Obtener usuario por id
GET http://localhost:3000/api/v1/usuarios/5a8da223-3d44-4a97-8020-6ff088c86e8f

### Crear un usuario
POST http://localhost:3000/api/v1/usuarios
Content-Type: application/json

{
  "username": "joe doe",
  "email": "joedoe@user.com"
}
